/* Automatically generated by po2tbl.sed from wavelan-applet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"No /proc/net/wireless", 2},
  {"Cannot read /proc/net/wireless", 3},
  {"WaveLan applet properties", 4},
  {"WaveLan Applet", 5},
  {"(C) 2001 Free Software Foundation ", 6},
  {"blablabla", 7},
  {"Properties...", 8},
  {"About...", 9},
  {"Can't create applet!\n", 10},
};

int _msg_tbl_length = 10;
