/* Automatically generated by po2tbl.sed from wavelan-applet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"No themes installed", 2},
  {"No /proc/net/wireless", 3},
  {"Cannot read /proc/net/wireless", 4},
  {"WaveLan applet properties", 5},
  {"WaveLan Applet", 6},
  {"(C) 2001 Free Software Foundation ", 7},
  {"blablabla", 8},
  {"Properties...", 9},
  {"About...", 10},
  {"Can't create applet!\n", 11},
  {"Theme", 12},
  {"Show signal strength in percentage", 13},
  {"Show dialog boxes", 14},
  {"Antialiase text", 15},
  {"Appearance", 16},
  {"Update interval (secs)", 17},
  {"Device", 18},
  {"Advanced", 19},
};

int _msg_tbl_length = 19;
