/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Theme");
gchar *s = N_("Show signal strength in percentage");
gchar *s = N_("Show dialog boxes");
gchar *s = N_("Appearance");
gchar *s = N_("Update interval (secs)");
gchar *s = N_("Device");
gchar *s = N_("Advanced");
